### ISSUE TITLE
isolate tests & extra dependencies

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/ecosystem-ci#8]
### isolate tests

copy all tests for a project to `_itenration` instead of repo root

### xtra dependencies

thinking about having
```yaml
dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/1.5.x
```
and also:
```yaml
dependencies:
  - name: Cython
    checkout: 3.56
```
which would do `pip install Cython==3.56`

### Motivation

simple cleaning in make or anywhere
